config/routes.rb
Rails.application.routes.draw do
  root :to => 'books#top'
  get 'top' => 'books#top',as: '/'
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit',as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] ='the post is successfully posted'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'the post is successfully updated'
      redirect_to book_path
    else
      flash[:notice] = 'the error occoured'
      render:new
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = 'destroy was successfully done'
      redirect_to books_path
    else
      flash[:notice] = 'destroy was failed'
      render :index
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="error_m">
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>
</div>


<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
  <%= link_to 'Show',book_path(@book.id) %>
  <%= link_to "Back",books_path %>
<% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<h1>Books</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
            <td><%= link_to "Show", book_path(book.id) %></td>
            <td><%= link_to "edit", edit_book_path(book.id) %></td>
            <td><%= link_to "Destroy",  destroy_book_path(book.id), method: :delete, data: { confirm: '削除しますか？' } %></td>
        </tr>
         <% end %>
    </tbody>
</table>
<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<h1>New book</h1>
<%= form_with model:@book,url:'/books',local: true do |f| %>
  <table>
    <tr><th>title</th></tr>
      <td><%= f.text_field :title %></td>
    <tr><th>body</th></tr>
      <td><%= f.text_area :body %></td>
    <tr><th></th></tr>
      <td><%= f.submit 'Create Book' %></td>
  </table>

<% end %>

app/views/books/new.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>


<h1>New books</h1>
<%= form_with model:@book,url:'/books',local: true do |f| %>
  <table>
    <tr><th>title</th></tr>
      <td><%= f.text_field :title %></td>
    <tr><th>body</th></tr>
      <td><%= f.text_area :body %></td>
    <tr><th></th></tr>
      <td><%= f.submit '送信' %></td>
  </table>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>



<p><strong>Title:</strong><%= @book.title %></p>
<p><strong>Body:</strong><%= @book.body %></p>
<%= link_to "edit",edit_book_path(@book.id) %>
|
<%= link_to "back",books_path %>

app/views/books/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>bookersでは、さまざまな書籍に関するあなたの意見や</br>印象を共有することができます</p>
<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>